[project]
name = "fastapi-boot-project"
version = "0.0.50"
description = "FastAPI tools"
readme = "README.md"
authors = [{ name = "hfdy", email = "hfdy09354121794@gmail.com" }]
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["fastapi_boot", "tests"]
